project_id = "txjglujklpxsfhedwwkl"

[functions.send-event-invitation]
verify_jwt = false

[functions.send-registration-confirmation]
verify_jwt = false

[functions.send-registration-notification]
verify_jwt = true

[functions.handle-registration-action]
verify_jwt = true

[functions.generate-description]
verify_jwt = true

[functions.predict-attendance]
verify_jwt = true

[functions.ai-assistant]
verify_jwt = false

[functions.validate-email-domain]
verify_jwt = false

[functions.verify-check-in]
verify_jwt = false